version: '3'
services:
  aws-iss:
    image: "bogdanmic/aws-iss:latest"
    container_name: aws-iss
    expose: 
      - 3000
    ports:
      - "3000:3000"
    environment:
      AWS_ACCESS_KEY_ID: "YOUR_AWS_ACCESS_KEY_ID"
      AWS_SECRET_ACCESS_KEY: "YOUR_AWS_SECRET_ACCESS_KEY"
    volumes:
      - /PATH/TO/YOUR-CONFIG.yml:/app/config/production.yml
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"