schedulers:
  ec2Schedulers:
    enabled: false
    startCron: "*/2 * * * * *"
    stopCron: "*/2 * * * * *"
  rdsSchedulers:
    enabled: false
    startCron: "*/2 * * * * *"
    stopCron: "*/2 * * * * *"

aws:
  region: "eu-west-1"
  interactiveInstances:
    ec2: []
    rds:  []